config/routes.rb
OpenStax::Accounts::Engine.routes.draw do
  # Redirect here if we don't know what to do (theoretically should not happen)
  root to: 'sessions#new'

  # Shortcut to OmniAuth route that redirects to the Accounts server
  # This is provided by OmniAuth and is not in the SessionsController
  post '/auth/openstax', to: ->(env) { [ 404, {}, [ '' ] ] }, as: 'openstax_login'

  if OpenStax::Accounts.configuration.enable_stubbing?
    # User profile route
    namespace :dev do
      resources :accounts, only: [:index, :create] do
        post 'become', on: :member
      end
    end
  end

  # OmniAuth local routes (SessionsController)
  scope module: 'sessions' do
    get 'auth/openstax/callback', action: :callback, as: :callback # Authentication success
    get 'auth/failure', action: :failure, as: :failure             # Authentication failure

    get 'login', action: :new # Redirects to /auth/openstax or stub
    match 'logout', action: :destroy, # Redirects to logout path or stub
                    via: OpenStax::Accounts.configuration.logout_via
    get 'profile', action: :profile # Redirects to profile path or stub
  end
end

app/models/openstax/accounts/account.rb
module OpenStax::Accounts
    class Account < ActiveRecord::Base
    USERNAME_DISCARDED_CHAR_REGEX = /[^A-Za-z\d_]/
    USERNAME_MAX_LENGTH = 50
    SYNC_ATTRIBUTES = [
      :openstax_uid,
      :username,
      :is_administrator,
      :first_name,
      :last_name,
      :full_name,
      :title,
      :self_reported_role,
      :faculty_status,
      :school_type,
      :school_location,
      :salesforce_contact_id,
      :support_identifier,
      :is_test,
      :is_kip,
      :grant_tutor_access
    ]

    attr_accessor :syncing

    enum faculty_status: [
      :no_faculty_info,
      :pending_faculty,
      :confirmed_faculty,
      :rejected_faculty
    ]

    enum role: [
      :unknown_role,
      :student,
      :instructor,
      :administrator,
      :librarian,
      :designer,
      :other,
      :adjunct,
      :homeschool,
      :researcher
    ]

    enum school_type: [
      :unknown_school_type,
      :other_school_type,
      :college,
      :high_school,
      :k12_school,
      :home_school
    ]

    enum school_location: [
      :unknown_school_location,
      :domestic_school,
      :foreign_school
    ]

    validates :faculty_status, :role, :school_type, :school_location, presence: true

    validates :uuid, presence: true, uniqueness: true
    validates :support_identifier, uniqueness: { allow_nil: true }

    before_update :update_openstax_accounts, if: :should_send_updates_to_accounts?

    def name
      (first_name || last_name) ? [first_name, last_name].compact.join(" ") : username
    end

    def casual_name
      first_name || username
    end

    def is_anonymous?
      false
    end

    def has_authenticated?
      !access_token.nil?
    end

    def valid_openstax_uid?
      !openstax_uid.nil? && openstax_uid > 0
    end

    def self_reported_role
      role
    end

    def self_reported_role=(role)
      self.role = role
    end

    protected

    def syncing_or_stubbing?
      syncing || OpenStax::Accounts.configuration.enable_stubbing?
    end

    def should_send_updates_to_accounts?
      !syncing_or_stubbing? && valid_openstax_uid?
    end

    def update_openstax_accounts
      OpenStax::Accounts::Api.update_account(self)
    end
  end
end

app/models/openstax/accounts/anonymous_account.rb
module OpenStax
  module Accounts
    class AnonymousAccount < Account
      include Singleton

      before_save { false }

      def initialize(attributes=nil)
        super
        self.id           = nil
        self.uuid         = nil
        self.openstax_uid = nil
        self.username     = 'anonymous'
        self.first_name   = 'Guest'
        self.last_name    = 'User'
      end

      def is_anonymous?
        true
      end
    end
  end
end

app/models/openstax/accounts/application_account.rb
module OpenStax
  module Accounts
    class ApplicationAccount
      attr_accessor :id, :application_id, :account, :unread_updates, :default_contact_info_id
    end
  end
end

app/controllers/openstax/accounts/application_controller.rb
module OpenStax
  module Accounts
    class ApplicationController < ::ActionController::Base
      include Lev::HandleWith

      skip_before_action :authenticate_user!, raise: false

      def configuration
        OpenStax::Accounts.configuration
      end
    end
  end
end

app/controllers/openstax/accounts/dev/accounts_controller.rb
module OpenStax
  module Accounts
    module Dev
      class AccountsController < OpenStax::Accounts::Dev::BaseController
        # Allow accessing from inside an iframe
        before_action :allow_iframe_access, only: :index

        def index
          handle_with AccountsSearch
        end

        def create
          handle_with(
            AccountsCreate,
            success: -> do
              username = @handler_result.outputs.account.username
              flash.notice = "Account with username \"#{username}\" created."
              redirect_to dev_accounts_path(search: { query: username })
            end,
            failure: -> do
              flash.alert = @handler_result.errors.first.translate
              redirect_to dev_accounts_path(search: { query: params.dig(:create, :username) })
            end
          )
        end

        def become
          @account = Account.find(params[:id])
          sign_in @account
          redirect_back key: :accounts_return_to, strategies: [:session]
        end

        private

        def allow_iframe_access
          response.headers.except! 'X-Frame-Options'
        end
      end
    end
  end
end

app/controllers/openstax/accounts/dev/base_controller.rb
module OpenStax
  module Accounts
    module Dev
      class BaseController < OpenStax::Accounts::ApplicationController
        before_action { raise SecurityTransgression if Rails.env.production? }
      end
    end
  end
end

app/controllers/openstax/accounts/remote_controller.rb
module OpenStax
  module Accounts
    class RemoteController < OpenStax::Accounts::ApplicationController

      def loader
        respond_to do |format|
          format.js
        end
      end

    end
  end
end

app/controllers/openstax/accounts/sessions_controller.rb
module OpenStax
  module Accounts
    class SessionsController < OpenStax::Accounts::ApplicationController
      def new
        if configuration.is_return_to_url_approved?(params[:return_to])
          store_url url: params[:return_to], key: :accounts_return_to, strategies: [:session]
        end
        store_fallback key: :accounts_return_to, strategies: [:session]

        if configuration.enable_stubbing?
          redirect_to dev_accounts_path
        else
          forwardable_params = params.permit(*configuration.forwardable_login_params).to_h
          redirect_to openstax_login_path(forwardable_params)
        end
      end

      def callback
        handle_with(
          SessionsCallback,
          success: -> do
            sign_in(@handler_result.outputs[:account])
            redirect_back key: :accounts_return_to, strategies: [:session]
          end,
          failure: -> { failure }
        )
      end

      def destroy
        # if a handler is configured, let it handle everything
        if configuration.logout_handler
          configuration.logout_handler.call(self)
        else
          # Unless we are stubbing, we redirect to a configurable URL, which is normally
          # (or at least eventually) the Accounts logout URL so that users can't sign back
          # in automagically.
          sign_out!
          redirect_to(configuration.enable_stubbing? ?
                        main_app.root_url :
                        configuration.logout_redirect_url(request), allow_other_host: true)
        end
      end

      def failure
        redirect_back key: :accounts_return_to, alert: 'Authentication failed, please try again.'
      end

      def profile
        # TODO: stub profile if stubbing is enabled
        redirect_to URI.join(configuration.openstax_accounts_url, 'profile').to_s
      end
    end
  end
end

app/helpers/openstax/accounts/application_helper.rb
module OpenStax
  module Accounts
    module ApplicationHelper

      def unless_errors(options={}, &block)
        options[:errors] ||= @handler_result.errors
        options[:errors_html_id] ||= OpenStax::Accounts.configuration.default_errors_html_id
        options[:errors_partial] ||= OpenStax::Accounts.configuration.default_errors_partial
        options[:trigger] ||= OpenStax::Accounts.configuration.default_errors_added_trigger

        if options[:errors].any? || flash[:alert]
          "$('##{options[:errors_html_id]}').html('#{ j(render options[:errors_partial], errors: options[:errors]) }').trigger('#{options[:trigger]}');".html_safe
        else
          ("$('##{options[:errors_html_id]}').html('');" + capture(&block)).html_safe
        end
      end

    end
  end
end

app/helpers/openstax/accounts/remote_helper.rb
module OpenStax
  module Accounts
    module RemoteHelper
      def accounts_loader_script_tag
        javascript_include_tag openstax_accounts.remote_js_loader_url
      end
    end
  end
end

app/views/openstax/accounts/dev/accounts/_search_results.html.erb
<% total_count = @handler_result.outputs.total_count
   accounts = @handler_result.outputs.items || [] %>

<div id='search-results-count'>
  <%= pluralize(total_count, 'user') %> found.
</div>

<div id='search-results-list'>
  <%= osu.action_list(
        records: accounts,
        list: {
          headings: ['UID', 'UUID', 'Username (click to sign in as)', 'Name'],
          widths: ['20%', '20%', '30%', '30%'],
          data_procs: [
            ->(account) { account.openstax_uid },
            ->(account) { account.uuid },
            ->(account) {
              link_to account.username, become_dev_account_path(account.id), method: :post
            },
            ->(account) { account.name || '---' }
          ]
        }
      ) %>
</div>

app/views/openstax/accounts/dev/accounts/index.html.erb
<div class="openstax-accounts development-login">
  <%= render partial: 'openstax/accounts/shared/attention' %>

  <h3>Create an Account</h3>

  <%= lev_form_for :create,
                   url: openstax_accounts.dev_accounts_path,
                   method: :post,
                   html: {class: 'form-inline'} do |f| %>


    <div class="form-group">
      <%= f.text_field :username, placeholder: 'Username' %>&nbsp;
      <%= f.select :role, OpenStax::Accounts::Account.roles.keys.map{|rr| [rr, rr]} %>&nbsp;
      <%= f.submit 'Create', class: 'btn btn-primary' %>
    </div>

  <% end %>

  <h3>Development Login</h3>

  <p>You need to login, but we're not connected to the Accounts server.<br>
  Search for a user below and click the sign in link next to him or her.</p>

  <%= render partial: 'openstax/accounts/shared/accounts/search',
             locals: {
               search_action_path: openstax_accounts.dev_accounts_path,
               search_results_partial: 'openstax/accounts/dev/accounts/search_results',
               remote: true,
               method: :get
             } %>

  <br>
</div>

app/views/openstax/accounts/dev/accounts/index.js.erb
<%= unless_errors alerts_html_id: 'dialog-local-alerts' do %>
  $("#search-results").html("<%= j(render 'openstax/accounts/dev/accounts/search_results') %>");
<% end %>

app/views/openstax/accounts/dev/accounts/login.html.erb
<div class="openstax-accounts development-login">

  <% handler_errors.each do |error| %>
    <%= error.translate %>
  <% end %>

  <%= osu.section_block "Development Login" do %>

    <p>You need to login, but we're not connected to the Accounts server.
    Search for a user below and click the sign in link next to him or her.</p>

    <%= render 'openstax/accounts/shared/accounts/index',
               :search_action_path => with_interceptor {
                  openstax_accounts.dev_accounts_path }},
               :remote => true %>

  <% end %>

</div>

app/views/openstax/accounts/dev/accounts/search.js.erb
<%= unless_errors alerts_html_id: 'dialog-local-alerts' do %>
  $("#search-results").html("<%= j(render 'openstax/accounts/dev/accounts/search_results') %>");
<% end %>